//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.GroupService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="GroupService.GroupService")]
    public interface GroupService {
        
        // CODEGEN: 消息 addGroupRequest 的包装名称(addGroupRequest)以后生成的消息协定与默认值(addGroup)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/GroupService/addGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.GroupService.addGroupResponse addGroup(com.baidu.api.sem.nms.v2.GroupService.addGroupRequest request);
        
        // CODEGEN: 消息 getGroupByGroupIdRequest 的包装名称(getGroupByGroupIdRequest)以后生成的消息协定与默认值(getGroupByGroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/GroupService/getGroupByGroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdResponse getGroupByGroupId(com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdRequest request);
        
        // CODEGEN: 消息 getGroupByCampaignIdRequest 的包装名称(getGroupByCampaignIdRequest)以后生成的消息协定与默认值(getGroupByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/GroupService/getGroupByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdResponse getGroupByCampaignId(com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdRequest request);
        
        // CODEGEN: 消息 getGroupIdByCampaignIdRequest 的包装名称(getGroupIdByCampaignIdRequest)以后生成的消息协定与默认值(getGroupIdByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/GroupService/getGroupIdByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdResponse getGroupIdByCampaignId(com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdRequest request);
        
        // CODEGEN: 消息 updateGroupRequest 的包装名称(updateGroupRequest)以后生成的消息协定与默认值(updateGroup)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/GroupService/updateGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.GroupService.updateGroupResponse updateGroup(com.baidu.api.sem.nms.v2.GroupService.updateGroupRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class GroupType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private long campaignIdField;
        
        private bool campaignIdFieldSpecified;
        
        private string groupNameField;
        
        private int priceField;
        
        private bool priceFieldSpecified;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private int excludeGenderField;
        
        private bool excludeGenderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
                this.RaisePropertyChanged("groupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool campaignIdSpecified {
            get {
                return this.campaignIdFieldSpecified;
            }
            set {
                this.campaignIdFieldSpecified = value;
                this.RaisePropertyChanged("campaignIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
                this.RaisePropertyChanged("priceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int excludeGender {
            get {
                return this.excludeGenderField;
            }
            set {
                this.excludeGenderField = value;
                this.RaisePropertyChanged("excludeGender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool excludeGenderSpecified {
            get {
                return this.excludeGenderFieldSpecified;
            }
            set {
                this.excludeGenderFieldSpecified = value;
                this.RaisePropertyChanged("excludeGenderSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addGroupRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addGroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public addGroupRequest() {
        }
        
        public addGroupRequest(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, GroupType[] groupTypes) {
            this.AuthHeader = AuthHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addGroupResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addGroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public addGroupResponse() {
        }
        
        public addGroupResponse(com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader, GroupType[] groupTypes) {
            this.ResHeader = ResHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupByGroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupByGroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] groupIds;
        
        public getGroupByGroupIdRequest() {
        }
        
        public getGroupByGroupIdRequest(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long[] groupIds) {
            this.AuthHeader = AuthHeader;
            this.groupIds = groupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupByGroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupByGroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public getGroupByGroupIdResponse() {
        }
        
        public getGroupByGroupIdResponse(com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader, GroupType[] groupTypes) {
            this.ResHeader = ResHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long campaignId;
        
        public getGroupByCampaignIdRequest() {
        }
        
        public getGroupByCampaignIdRequest(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long campaignId) {
            this.AuthHeader = AuthHeader;
            this.campaignId = campaignId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public getGroupByCampaignIdResponse() {
        }
        
        public getGroupByCampaignIdResponse(com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader, GroupType[] groupTypes) {
            this.ResHeader = ResHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupIdByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupIdByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long campaignId;
        
        public getGroupIdByCampaignIdRequest() {
        }
        
        public getGroupIdByCampaignIdRequest(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long campaignId) {
            this.AuthHeader = AuthHeader;
            this.campaignId = campaignId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupIdByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getGroupIdByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] groupIds;
        
        public getGroupIdByCampaignIdResponse() {
        }
        
        public getGroupIdByCampaignIdResponse(com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader, long[] groupIds) {
            this.ResHeader = ResHeader;
            this.groupIds = groupIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGroupRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateGroupRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public updateGroupRequest() {
        }
        
        public updateGroupRequest(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, GroupType[] groupTypes) {
            this.AuthHeader = AuthHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateGroupResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateGroupResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GroupType[] groupTypes;
        
        public updateGroupResponse() {
        }
        
        public updateGroupResponse(com.baidu.api.sem.nms.v2.GroupService.ResHeader ResHeader, GroupType[] groupTypes) {
            this.ResHeader = ResHeader;
            this.groupTypes = groupTypes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupServiceChannel : com.baidu.api.sem.nms.v2.GroupService.GroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.GroupService.GroupService>, com.baidu.api.sem.nms.v2.GroupService.GroupService {
        
        public GroupServiceClient() {
        }
        
        public GroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.GroupService.addGroupResponse com.baidu.api.sem.nms.v2.GroupService.GroupService.addGroup(com.baidu.api.sem.nms.v2.GroupService.addGroupRequest request) {
            return base.Channel.addGroup(request);
        }
        
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader addGroup(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, ref GroupType[] groupTypes) {
            com.baidu.api.sem.nms.v2.GroupService.addGroupRequest inValue = new com.baidu.api.sem.nms.v2.GroupService.addGroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupTypes = groupTypes;
            com.baidu.api.sem.nms.v2.GroupService.addGroupResponse retVal = ((com.baidu.api.sem.nms.v2.GroupService.GroupService)(this)).addGroup(inValue);
            groupTypes = retVal.groupTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdResponse com.baidu.api.sem.nms.v2.GroupService.GroupService.getGroupByGroupId(com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdRequest request) {
            return base.Channel.getGroupByGroupId(request);
        }
        
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader getGroupByGroupId(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long[] groupIds, out GroupType[] groupTypes) {
            com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdRequest inValue = new com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupIds = groupIds;
            com.baidu.api.sem.nms.v2.GroupService.getGroupByGroupIdResponse retVal = ((com.baidu.api.sem.nms.v2.GroupService.GroupService)(this)).getGroupByGroupId(inValue);
            groupTypes = retVal.groupTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdResponse com.baidu.api.sem.nms.v2.GroupService.GroupService.getGroupByCampaignId(com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdRequest request) {
            return base.Channel.getGroupByCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader getGroupByCampaignId(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long campaignId, out GroupType[] groupTypes) {
            com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignId = campaignId;
            com.baidu.api.sem.nms.v2.GroupService.getGroupByCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.GroupService.GroupService)(this)).getGroupByCampaignId(inValue);
            groupTypes = retVal.groupTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdResponse com.baidu.api.sem.nms.v2.GroupService.GroupService.getGroupIdByCampaignId(com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdRequest request) {
            return base.Channel.getGroupIdByCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader getGroupIdByCampaignId(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, long campaignId, out long[] groupIds) {
            com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignId = campaignId;
            com.baidu.api.sem.nms.v2.GroupService.getGroupIdByCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.GroupService.GroupService)(this)).getGroupIdByCampaignId(inValue);
            groupIds = retVal.groupIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.GroupService.updateGroupResponse com.baidu.api.sem.nms.v2.GroupService.GroupService.updateGroup(com.baidu.api.sem.nms.v2.GroupService.updateGroupRequest request) {
            return base.Channel.updateGroup(request);
        }
        
        public com.baidu.api.sem.nms.v2.GroupService.ResHeader updateGroup(com.baidu.api.sem.nms.v2.GroupService.AuthHeader AuthHeader, ref GroupType[] groupTypes) {
            com.baidu.api.sem.nms.v2.GroupService.updateGroupRequest inValue = new com.baidu.api.sem.nms.v2.GroupService.updateGroupRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupTypes = groupTypes;
            com.baidu.api.sem.nms.v2.GroupService.updateGroupResponse retVal = ((com.baidu.api.sem.nms.v2.GroupService.GroupService)(this)).updateGroup(inValue);
            groupTypes = retVal.groupTypes;
            return retVal.ResHeader;
        }
    }
}
