//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.AccountFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="AccountFileService.AccountFileService")]
    public interface AccountFileService {
        
        // CODEGEN: 消息 getAccountFileIdRequest 的包装名称(getAccountFileIdRequest)以后生成的消息协定与默认值(getAccountFileId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AccountFileService/getAccountFileId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdResponse getAccountFileId(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdRequest request);
        
        // CODEGEN: 消息 getAccountFileStateRequest 的包装名称(getAccountFileStateRequest)以后生成的消息协定与默认值(getAccountFileState)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AccountFileService/getAccountFileState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateResponse getAccountFileState(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateRequest request);
        
        // CODEGEN: 消息 getAccountFileUrlRequest 的包装名称(getAccountFileUrlRequest)以后生成的消息协定与默认值(getAccountFileUrl)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AccountFileService/getAccountFileUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlResponse getAccountFileUrl(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class AccountFileRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long[] campaignIdsField;
        
        private int formatField;
        
        private bool formatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long[] campaignIds {
            get {
                return this.campaignIdsField;
            }
            set {
                this.campaignIdsField = value;
                this.RaisePropertyChanged("campaignIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatSpecified {
            get {
                return this.formatFieldSpecified;
            }
            set {
                this.formatFieldSpecified = value;
                this.RaisePropertyChanged("formatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public com.baidu.api.sem.nms.v2.AccountFileService.AccountFileRequestType accountFileRequestType;
        
        public getAccountFileIdRequest() {
        }
        
        public getAccountFileIdRequest(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, com.baidu.api.sem.nms.v2.AccountFileService.AccountFileRequestType accountFileRequestType) {
            this.AuthHeader = AuthHeader;
            this.accountFileRequestType = accountFileRequestType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileId;
        
        public getAccountFileIdResponse() {
        }
        
        public getAccountFileIdResponse(com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader, string fileId) {
            this.ResHeader = ResHeader;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileStateRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileId;
        
        public getAccountFileStateRequest() {
        }
        
        public getAccountFileStateRequest(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, string fileId) {
            this.AuthHeader = AuthHeader;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileStateResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileStateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isGenerated;
        
        public getAccountFileStateResponse() {
        }
        
        public getAccountFileStateResponse(com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader, int isGenerated) {
            this.ResHeader = ResHeader;
            this.isGenerated = isGenerated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileUrlRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileId;
        
        public getAccountFileUrlRequest() {
        }
        
        public getAccountFileUrlRequest(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, string fileId) {
            this.AuthHeader = AuthHeader;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAccountFileUrlResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAccountFileUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string md5;
        
        public getAccountFileUrlResponse() {
        }
        
        public getAccountFileUrlResponse(com.baidu.api.sem.nms.v2.AccountFileService.ResHeader ResHeader, string filePath, string md5) {
            this.ResHeader = ResHeader;
            this.filePath = filePath;
            this.md5 = md5;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountFileServiceChannel : com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountFileServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService>, com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService {
        
        public AccountFileServiceClient() {
        }
        
        public AccountFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdResponse com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService.getAccountFileId(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdRequest request) {
            return base.Channel.getAccountFileId(request);
        }
        
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader getAccountFileId(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, com.baidu.api.sem.nms.v2.AccountFileService.AccountFileRequestType accountFileRequestType, out string fileId) {
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdRequest inValue = new com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.accountFileRequestType = accountFileRequestType;
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileIdResponse retVal = ((com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService)(this)).getAccountFileId(inValue);
            fileId = retVal.fileId;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateResponse com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService.getAccountFileState(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateRequest request) {
            return base.Channel.getAccountFileState(request);
        }
        
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader getAccountFileState(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, string fileId, out int isGenerated) {
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateRequest inValue = new com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.fileId = fileId;
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileStateResponse retVal = ((com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService)(this)).getAccountFileState(inValue);
            isGenerated = retVal.isGenerated;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlResponse com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService.getAccountFileUrl(com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlRequest request) {
            return base.Channel.getAccountFileUrl(request);
        }
        
        public com.baidu.api.sem.nms.v2.AccountFileService.ResHeader getAccountFileUrl(com.baidu.api.sem.nms.v2.AccountFileService.AuthHeader AuthHeader, string fileId, out string filePath, out string md5) {
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlRequest inValue = new com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.fileId = fileId;
            com.baidu.api.sem.nms.v2.AccountFileService.getAccountFileUrlResponse retVal = ((com.baidu.api.sem.nms.v2.AccountFileService.AccountFileService)(this)).getAccountFileUrl(inValue);
            filePath = retVal.filePath;
            md5 = retVal.md5;
            return retVal.ResHeader;
        }
    }
}
