
/*
 * 
 */

package com.baidu.api.sem.nms.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Dec 23 10:16:26 CST 2011
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "AccountService", 
                  wsdlLocation = "https://api.baidu.com/sem/nms/v2/AccountService?wsdl",
                  targetNamespace = "https://api.baidu.com/sem/nms/v2") 
public class AccountService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("https://api.baidu.com/sem/nms/v2", "AccountService");
    public final static QName AccountService = new QName("https://api.baidu.com/sem/nms/v2", "AccountService");
    static {
        URL url = null;
        try {
            url = new URL("https://api.baidu.com/sem/nms/v2/AccountService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://api.baidu.com/sem/nms/v2/AccountService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AccountService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccountService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountService")
    public AccountService getAccountService() {
        return super.getPort(AccountService, AccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountService
     */
    @WebEndpoint(name = "AccountService")
    public AccountService getAccountService(WebServiceFeature... features) {
        return super.getPort(AccountService, AccountService.class, features);
    }

}
