
/*
 * 
 */

package com.baidu.api.sem.nms.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Dec 23 10:17:48 CST 2011
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "CodeService", 
                  wsdlLocation = "https://api.baidu.com/sem/nms/v2/CodeService?wsdl",
                  targetNamespace = "https://api.baidu.com/sem/nms/v2") 
public class CodeService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("https://api.baidu.com/sem/nms/v2", "CodeService");
    public final static QName CodeService = new QName("https://api.baidu.com/sem/nms/v2", "CodeService");
    static {
        URL url = null;
        try {
            url = new URL("https://api.baidu.com/sem/nms/v2/CodeService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://api.baidu.com/sem/nms/v2/CodeService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CodeService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CodeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CodeService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CodeService
     */
    @WebEndpoint(name = "CodeService")
    public CodeService getCodeService() {
        return super.getPort(CodeService, CodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CodeService
     */
    @WebEndpoint(name = "CodeService")
    public CodeService getCodeService(WebServiceFeature... features) {
        return super.getPort(CodeService, CodeService.class, features);
    }

}
