package com.baidu.api.sem.nms.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Dec 23 10:17:48 CST 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "https://api.baidu.com/sem/nms/v2", name = "CodeService")
@XmlSeeAlso({com.baidu.api.sem.common.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CodeService {

    @WebResult(name = "getAllCategoryResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/CodeService/getAllCategory")
    public GetAllCategoryResponse getAllCategory(
        @WebParam(partName = "parameters", name = "getAllCategoryRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetAllCategoryRequest parameters
    );

    @WebResult(name = "getAllRegionResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/CodeService/getAllRegion")
    public GetAllRegionResponse getAllRegion(
        @WebParam(partName = "parameters", name = "getAllRegionRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetAllRegionRequest parameters
    );
}
