
/*
 * 
 */

package com.baidu.api.sem.nms.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Jan 11 14:33:23 CST 2012
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "GroupService", 
                  wsdlLocation = "https://api.baidu.com/sem/nms/v2/GroupService?wsdl",
                  targetNamespace = "https://api.baidu.com/sem/nms/v2") 
public class GroupService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("https://api.baidu.com/sem/nms/v2", "GroupService");
    public final static QName GroupService = new QName("https://api.baidu.com/sem/nms/v2", "GroupService");
    static {
        URL url = null;
        try {
            url = new URL("https://api.baidu.com/sem/nms/v2/GroupService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://api.baidu.com/sem/nms/v2/GroupService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GroupService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GroupService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GroupService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns GroupService
     */
    @WebEndpoint(name = "GroupService")
    public GroupService getGroupService() {
        return super.getPort(GroupService, GroupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GroupService
     */
    @WebEndpoint(name = "GroupService")
    public GroupService getGroupService(WebServiceFeature... features) {
        return super.getPort(GroupService, GroupService.class, features);
    }

}
