package com.baidu.api.sem.nms.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Wed Jan 11 14:33:23 CST 2012
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "https://api.baidu.com/sem/nms/v2", name = "GroupService")
@XmlSeeAlso({com.baidu.api.sem.common.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GroupService {

    @WebResult(name = "getGroupByGroupIdResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupService/getGroupByGroupId")
    public GetGroupByGroupIdResponse getGroupByGroupId(
        @WebParam(partName = "parameters", name = "getGroupByGroupIdRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetGroupByGroupIdRequest parameters
    );

    @WebResult(name = "updateGroupResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupService/updateGroup")
    public UpdateGroupResponse updateGroup(
        @WebParam(partName = "parameters", name = "updateGroupRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        UpdateGroupRequest parameters
    );

    @WebResult(name = "getGroupByCampaignIdResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupService/getGroupByCampaignId")
    public GetGroupByCampaignIdResponse getGroupByCampaignId(
        @WebParam(partName = "parameters", name = "getGroupByCampaignIdRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetGroupByCampaignIdRequest parameters
    );

    @WebResult(name = "getGroupIdByCampaignIdResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupService/getGroupIdByCampaignId")
    public GetGroupIdByCampaignIdResponse getGroupIdByCampaignId(
        @WebParam(partName = "parameters", name = "getGroupIdByCampaignIdRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetGroupIdByCampaignIdRequest parameters
    );

    @WebResult(name = "addGroupResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupService/addGroup")
    public AddGroupResponse addGroup(
        @WebParam(partName = "parameters", name = "addGroupRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        AddGroupRequest parameters
    );
}
