package com.baidu.api.sem.nms.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Fri Dec 23 14:24:25 CST 2011
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "https://api.baidu.com/sem/nms/v2", name = "GroupConfigService")
@XmlSeeAlso({com.baidu.api.sem.common.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GroupConfigService {

    @WebResult(name = "setRegionConfigResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setRegionConfig")
    public SetRegionConfigResponse setRegionConfig(
        @WebParam(partName = "parameters", name = "setRegionConfigRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetRegionConfigRequest parameters
    );

    @WebResult(name = "getRegionConfigResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getRegionConfig")
    public GetRegionConfigResponse getRegionConfig(
        @WebParam(partName = "parameters", name = "getRegionConfigRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetRegionConfigRequest parameters
    );

    @WebResult(name = "getSiteConfigResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getSiteConfig")
    public GetSiteConfigResponse getSiteConfig(
        @WebParam(partName = "parameters", name = "getSiteConfigRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetSiteConfigRequest parameters
    );

    @WebResult(name = "setSiteUrlResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setSiteUrl")
    public SetSiteUrlResponse setSiteUrl(
        @WebParam(partName = "parameters", name = "setSiteUrlRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetSiteUrlRequest parameters
    );

    @WebResult(name = "getExcludeIpResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getExcludeIp")
    public GetExcludeIpResponse getExcludeIp(
        @WebParam(partName = "parameters", name = "getExcludeIpRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetExcludeIpRequest parameters
    );

    @WebResult(name = "setTargetInfoResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setTargetInfo")
    public SetTargetInfoResponse setTargetInfo(
        @WebParam(partName = "parameters", name = "setTargetInfoRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetTargetInfoRequest parameters
    );

    @WebResult(name = "getExcludeSiteResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getExcludeSite")
    public GetExcludeSiteResponse getExcludeSite(
        @WebParam(partName = "parameters", name = "getExcludeSiteRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetExcludeSiteRequest parameters
    );

    @WebResult(name = "getCtKeywordResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getCtKeyword")
    public GetCtKeywordResponse getCtKeyword(
        @WebParam(partName = "parameters", name = "getCtKeywordRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetCtKeywordRequest parameters
    );

    @WebResult(name = "setSiteConfigResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setSiteConfig")
    public SetSiteConfigResponse setSiteConfig(
        @WebParam(partName = "parameters", name = "setSiteConfigRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetSiteConfigRequest parameters
    );

    @WebResult(name = "setExcludeSiteResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setExcludeSite")
    public SetExcludeSiteResponse setExcludeSite(
        @WebParam(partName = "parameters", name = "setExcludeSiteRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetExcludeSiteRequest parameters
    );

    @WebResult(name = "setTradeSitePriceResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setTradeSitePrice")
    public SetTradeSitePriceResponse setTradeSitePrice(
        @WebParam(partName = "parameters", name = "setTradeSitePriceRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetTradeSitePriceRequest parameters
    );

    @WebResult(name = "getTradeSitePriceResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getTradeSitePrice")
    public GetTradeSitePriceResponse getTradeSitePrice(
        @WebParam(partName = "parameters", name = "getTradeSitePriceRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetTradeSitePriceRequest parameters
    );

    @WebResult(name = "setExcludeIpResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/setExcludeIp")
    public SetExcludeIpResponse setExcludeIp(
        @WebParam(partName = "parameters", name = "setExcludeIpRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        SetExcludeIpRequest parameters
    );

    @WebResult(name = "getSiteUrlResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getSiteUrl")
    public GetSiteUrlResponse getSiteUrl(
        @WebParam(partName = "parameters", name = "getSiteUrlRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetSiteUrlRequest parameters
    );

    @WebResult(name = "getQtKeywordResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/sms/v2/AccountService/getQtKeyword")
    public GetQtKeywordResponse getQtKeyword(
        @WebParam(partName = "parameters", name = "getQtKeywordRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetQtKeywordRequest parameters
    );

    @WebResult(name = "getTargetInfoResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/GroupConfigService/getTargetInfo")
    public GetTargetInfoResponse getTargetInfo(
        @WebParam(partName = "parameters", name = "getTargetInfoRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetTargetInfoRequest parameters
    );
}
