package com.baidu.api.sem.nms.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jan 09 15:00:28 CST 2012
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "https://api.baidu.com/sem/nms/v2", name = "ReportService")
@XmlSeeAlso({com.baidu.api.sem.common.v2.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReportService {

    @WebResult(name = "getReportStateResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/ReportService/getReportState")
    public GetReportStateResponse getReportState(
        @WebParam(partName = "parameters", name = "getReportStateRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetReportStateRequest parameters
    );

    @WebResult(name = "getReportFileUrlResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/ReportService/getReportFileUrl")
    public GetReportFileUrlResponse getReportFileUrl(
        @WebParam(partName = "parameters", name = "getReportFileUrlRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetReportFileUrlRequest parameters
    );

    @WebResult(name = "getReportIdResponse", targetNamespace = "https://api.baidu.com/sem/nms/v2", partName = "parameters")
    @WebMethod(action = "https://api.baidu.com/sem/nms/v2/ReportService/getReportId")
    public GetReportIdResponse getReportId(
        @WebParam(partName = "parameters", name = "getReportIdRequest", targetNamespace = "https://api.baidu.com/sem/nms/v2")
        GetReportIdRequest parameters
    );
}
