//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="ReportService.ReportService")]
    public interface ReportService {
        
        // CODEGEN: 消息 getReportIdRequest 的包装名称(getReportIdRequest)以后生成的消息协定与默认值(getReportId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/ReportService/getReportId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.ReportService.getReportIdResponse getReportId(com.baidu.api.sem.nms.v2.ReportService.getReportIdRequest request);
        
        // CODEGEN: 消息 getReportStateRequest 的包装名称(getReportStateRequest)以后生成的消息协定与默认值(getReportState)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/ReportService/getReportState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.ReportService.getReportStateResponse getReportState(com.baidu.api.sem.nms.v2.ReportService.getReportStateRequest request);
        
        // CODEGEN: 消息 getReportFileUrlRequest 的包装名称(getReportFileUrlRequest)以后生成的消息协定与默认值(getReportFileUrl)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/ReportService/getReportFileUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlResponse getReportFileUrl(com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class ReportRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] performanceDataField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private bool idOnlyField;
        
        private bool idOnlyFieldSpecified;
        
        private int reportTypeField;
        
        private int statRangeField;
        
        private bool statRangeFieldSpecified;
        
        private long[] statIdsField;
        
        private int formatField;
        
        private bool formatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performanceData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] performanceData {
            get {
                return this.performanceDataField;
            }
            set {
                this.performanceDataField = value;
                this.RaisePropertyChanged("performanceData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool idOnly {
            get {
                return this.idOnlyField;
            }
            set {
                this.idOnlyField = value;
                this.RaisePropertyChanged("idOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOnlySpecified {
            get {
                return this.idOnlyFieldSpecified;
            }
            set {
                this.idOnlyFieldSpecified = value;
                this.RaisePropertyChanged("idOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
                this.RaisePropertyChanged("reportType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int statRange {
            get {
                return this.statRangeField;
            }
            set {
                this.statRangeField = value;
                this.RaisePropertyChanged("statRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statRangeSpecified {
            get {
                return this.statRangeFieldSpecified;
            }
            set {
                this.statRangeFieldSpecified = value;
                this.RaisePropertyChanged("statRangeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long[] statIds {
            get {
                return this.statIdsField;
            }
            set {
                this.statIdsField = value;
                this.RaisePropertyChanged("statIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatSpecified {
            get {
                return this.formatFieldSpecified;
            }
            set {
                this.formatFieldSpecified = value;
                this.RaisePropertyChanged("formatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public com.baidu.api.sem.nms.v2.ReportService.ReportRequestType reportRequestType;
        
        public getReportIdRequest() {
        }
        
        public getReportIdRequest(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, com.baidu.api.sem.nms.v2.ReportService.ReportRequestType reportRequestType) {
            this.AuthHeader = AuthHeader;
            this.reportRequestType = reportRequestType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportId;
        
        public getReportIdResponse() {
        }
        
        public getReportIdResponse(com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader, string reportId) {
            this.ResHeader = ResHeader;
            this.reportId = reportId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportStateRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportId;
        
        public getReportStateRequest() {
        }
        
        public getReportStateRequest(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, string reportId) {
            this.AuthHeader = AuthHeader;
            this.reportId = reportId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportStateResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportStateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isGenerated;
        
        public getReportStateResponse() {
        }
        
        public getReportStateResponse(com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader, int isGenerated) {
            this.ResHeader = ResHeader;
            this.isGenerated = isGenerated;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportFileUrlRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportFileUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportId;
        
        public getReportFileUrlRequest() {
        }
        
        public getReportFileUrlRequest(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, string reportId) {
            this.AuthHeader = AuthHeader;
            this.reportId = reportId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReportFileUrlResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getReportFileUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reportFilePath;
        
        public getReportFileUrlResponse() {
        }
        
        public getReportFileUrlResponse(com.baidu.api.sem.nms.v2.ReportService.ResHeader ResHeader, string reportFilePath) {
            this.ResHeader = ResHeader;
            this.reportFilePath = reportFilePath;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportServiceChannel : com.baidu.api.sem.nms.v2.ReportService.ReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.ReportService.ReportService>, com.baidu.api.sem.nms.v2.ReportService.ReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.ReportService.getReportIdResponse com.baidu.api.sem.nms.v2.ReportService.ReportService.getReportId(com.baidu.api.sem.nms.v2.ReportService.getReportIdRequest request) {
            return base.Channel.getReportId(request);
        }
        
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader getReportId(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, com.baidu.api.sem.nms.v2.ReportService.ReportRequestType reportRequestType, out string reportId) {
            com.baidu.api.sem.nms.v2.ReportService.getReportIdRequest inValue = new com.baidu.api.sem.nms.v2.ReportService.getReportIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.reportRequestType = reportRequestType;
            com.baidu.api.sem.nms.v2.ReportService.getReportIdResponse retVal = ((com.baidu.api.sem.nms.v2.ReportService.ReportService)(this)).getReportId(inValue);
            reportId = retVal.reportId;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.ReportService.getReportStateResponse com.baidu.api.sem.nms.v2.ReportService.ReportService.getReportState(com.baidu.api.sem.nms.v2.ReportService.getReportStateRequest request) {
            return base.Channel.getReportState(request);
        }
        
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader getReportState(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, string reportId, out int isGenerated) {
            com.baidu.api.sem.nms.v2.ReportService.getReportStateRequest inValue = new com.baidu.api.sem.nms.v2.ReportService.getReportStateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.reportId = reportId;
            com.baidu.api.sem.nms.v2.ReportService.getReportStateResponse retVal = ((com.baidu.api.sem.nms.v2.ReportService.ReportService)(this)).getReportState(inValue);
            isGenerated = retVal.isGenerated;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlResponse com.baidu.api.sem.nms.v2.ReportService.ReportService.getReportFileUrl(com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlRequest request) {
            return base.Channel.getReportFileUrl(request);
        }
        
        public com.baidu.api.sem.nms.v2.ReportService.ResHeader getReportFileUrl(com.baidu.api.sem.nms.v2.ReportService.AuthHeader AuthHeader, string reportId, out string reportFilePath) {
            com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlRequest inValue = new com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.reportId = reportId;
            com.baidu.api.sem.nms.v2.ReportService.getReportFileUrlResponse retVal = ((com.baidu.api.sem.nms.v2.ReportService.ReportService)(this)).getReportFileUrl(inValue);
            reportFilePath = retVal.reportFilePath;
            return retVal.ResHeader;
        }
    }
}
