//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.CampaignService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="CampaignService.CampaignService")]
    public interface CampaignService {
        
        // CODEGEN: 消息 addCampaignRequest 的包装名称(addCampaignRequest)以后生成的消息协定与默认值(addCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/CampaignService/addCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.CampaignService.addCampaignResponse addCampaign(com.baidu.api.sem.nms.v2.CampaignService.addCampaignRequest request);
        
        // CODEGEN: 消息 getCampaignByCampaignIdRequest 的包装名称(getCampaignByCampaignIdRequest)以后生成的消息协定与默认值(getCampaignByCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/CampaignService/getCampaignByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdResponse getCampaignByCampaignId(com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdRequest request);
        
        // CODEGEN: 消息 getCampaignRequest 的包装名称(getCampaignRequest)以后生成的消息协定与默认值(getCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/CampaignService/getCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignResponse getCampaign(com.baidu.api.sem.nms.v2.CampaignService.getCampaignRequest request);
        
        // CODEGEN: 消息 getCampaignIdRequest 的包装名称(getCampaignIdRequest)以后生成的消息协定与默认值(getCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/CampaignService/getCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdResponse getCampaignId(com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdRequest request);
        
        // CODEGEN: 消息 updateCampaignRequest 的包装名称(updateCampaignRequest)以后生成的消息协定与默认值(updateCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/CampaignService/updateCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.CampaignService.updateCampaignResponse updateCampaign(com.baidu.api.sem.nms.v2.CampaignService.updateCampaignRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class ScheduleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int weekDayField;
        
        private int startTimeField;
        
        private int endTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int weekDay {
            get {
                return this.weekDayField;
            }
            set {
                this.weekDayField = value;
                this.RaisePropertyChanged("weekDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("endTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class CampaignType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaignIdField;
        
        private bool campaignIdFieldSpecified;
        
        private string campaignNameField;
        
        private int budgetField;
        
        private bool budgetFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private ScheduleType[] scheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool campaignIdSpecified {
            get {
                return this.campaignIdFieldSpecified;
            }
            set {
                this.campaignIdFieldSpecified = value;
                this.RaisePropertyChanged("campaignIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string campaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
                this.RaisePropertyChanged("campaignName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int budget {
            get {
                return this.budgetField;
            }
            set {
                this.budgetField = value;
                this.RaisePropertyChanged("budget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool budgetSpecified {
            get {
                return this.budgetFieldSpecified;
            }
            set {
                this.budgetFieldSpecified = value;
                this.RaisePropertyChanged("budgetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("startDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
                this.RaisePropertyChanged("endDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("schedule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ScheduleType[] schedule {
            get {
                return this.scheduleField;
            }
            set {
                this.scheduleField = value;
                this.RaisePropertyChanged("schedule");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public addCampaignRequest() {
        }
        
        public addCampaignRequest(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, CampaignType[] campaignTypes) {
            this.AuthHeader = AuthHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public addCampaignResponse() {
        }
        
        public addCampaignResponse(com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader, CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignByCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignByCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getCampaignByCampaignIdRequest() {
        }
        
        public getCampaignByCampaignIdRequest(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignByCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignByCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public getCampaignByCampaignIdResponse() {
        }
        
        public getCampaignByCampaignIdResponse(com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader, CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader;
        
        public getCampaignRequest() {
        }
        
        public getCampaignRequest(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public getCampaignResponse() {
        }
        
        public getCampaignResponse(com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader, CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader;
        
        public getCampaignIdRequest() {
        }
        
        public getCampaignIdRequest(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getCampaignIdResponse() {
        }
        
        public getCampaignIdResponse(com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader, long[] campaignIds) {
            this.ResHeader = ResHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public updateCampaignRequest() {
        }
        
        public updateCampaignRequest(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, CampaignType[] campaignTypes) {
            this.AuthHeader = AuthHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CampaignType[] campaignTypes;
        
        public updateCampaignResponse() {
        }
        
        public updateCampaignResponse(com.baidu.api.sem.nms.v2.CampaignService.ResHeader ResHeader, CampaignType[] campaignTypes) {
            this.ResHeader = ResHeader;
            this.campaignTypes = campaignTypes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CampaignServiceChannel : com.baidu.api.sem.nms.v2.CampaignService.CampaignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampaignServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.CampaignService.CampaignService>, com.baidu.api.sem.nms.v2.CampaignService.CampaignService {
        
        public CampaignServiceClient() {
        }
        
        public CampaignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.CampaignService.addCampaignResponse com.baidu.api.sem.nms.v2.CampaignService.CampaignService.addCampaign(com.baidu.api.sem.nms.v2.CampaignService.addCampaignRequest request) {
            return base.Channel.addCampaign(request);
        }
        
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader addCampaign(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, ref CampaignType[] campaignTypes) {
            com.baidu.api.sem.nms.v2.CampaignService.addCampaignRequest inValue = new com.baidu.api.sem.nms.v2.CampaignService.addCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignTypes = campaignTypes;
            com.baidu.api.sem.nms.v2.CampaignService.addCampaignResponse retVal = ((com.baidu.api.sem.nms.v2.CampaignService.CampaignService)(this)).addCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdResponse com.baidu.api.sem.nms.v2.CampaignService.CampaignService.getCampaignByCampaignId(com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdRequest request) {
            return base.Channel.getCampaignByCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader getCampaignByCampaignId(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, long[] campaignIds, out CampaignType[] campaignTypes) {
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignByCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.CampaignService.CampaignService)(this)).getCampaignByCampaignId(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignResponse com.baidu.api.sem.nms.v2.CampaignService.CampaignService.getCampaign(com.baidu.api.sem.nms.v2.CampaignService.getCampaignRequest request) {
            return base.Channel.getCampaign(request);
        }
        
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader getCampaign(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, out CampaignType[] campaignTypes) {
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignRequest inValue = new com.baidu.api.sem.nms.v2.CampaignService.getCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignResponse retVal = ((com.baidu.api.sem.nms.v2.CampaignService.CampaignService)(this)).getCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdResponse com.baidu.api.sem.nms.v2.CampaignService.CampaignService.getCampaignId(com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdRequest request) {
            return base.Channel.getCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader getCampaignId(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, out long[] campaignIds) {
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            com.baidu.api.sem.nms.v2.CampaignService.getCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.CampaignService.CampaignService)(this)).getCampaignId(inValue);
            campaignIds = retVal.campaignIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.CampaignService.updateCampaignResponse com.baidu.api.sem.nms.v2.CampaignService.CampaignService.updateCampaign(com.baidu.api.sem.nms.v2.CampaignService.updateCampaignRequest request) {
            return base.Channel.updateCampaign(request);
        }
        
        public com.baidu.api.sem.nms.v2.CampaignService.ResHeader updateCampaign(com.baidu.api.sem.nms.v2.CampaignService.AuthHeader AuthHeader, ref CampaignType[] campaignTypes) {
            com.baidu.api.sem.nms.v2.CampaignService.updateCampaignRequest inValue = new com.baidu.api.sem.nms.v2.CampaignService.updateCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignTypes = campaignTypes;
            com.baidu.api.sem.nms.v2.CampaignService.updateCampaignResponse retVal = ((com.baidu.api.sem.nms.v2.CampaignService.CampaignService)(this)).updateCampaign(inValue);
            campaignTypes = retVal.campaignTypes;
            return retVal.ResHeader;
        }
    }
}
