//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.FCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="FCService.FCService")]
    public interface FCService {
        
        // CODEGEN: 消息 getFCCampaignRequest 的包装名称(getFCCampaignRequest)以后生成的消息协定与默认值(getFCCampaign)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignResponse getFCCampaign(com.baidu.api.sem.nms.v2.FCService.getFCCampaignRequest request);
        
        // CODEGEN: 消息 getFCCampaignIdRequest 的包装名称(getFCCampaignIdRequest)以后生成的消息协定与默认值(getFCCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdResponse getFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdRequest request);
        
        // CODEGEN: 消息 getFCCampaignByFCCampaignIdRequest 的包装名称(getFCCampaignByFCCampaignIdRequest)以后生成的消息协定与默认值(getFCCampaignByFCCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCCampaignByFCCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdResponse getFCCampaignByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdRequest request);
        
        // CODEGEN: 消息 getFCUnitByFCCampaignIdRequest 的包装名称(getFCUnitByFCCampaignIdRequest)以后生成的消息协定与默认值(getFCUnitByFCCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCUnitByFCCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdResponse getFCUnitByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdRequest request);
        
        // CODEGEN: 消息 getFCUnitIdByFCCampaignIdRequest 的包装名称(getFCUnitIdByFCCampaignIdRequest)以后生成的消息协定与默认值(getFCUnitIdByFCCampaignId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCUnitIdByFCCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdResponse getFCUnitIdByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdRequest request);
        
        // CODEGEN: 消息 getFCUnitByFCUnitIdRequest 的包装名称(getFCUnitByFCUnitIdRequest)以后生成的消息协定与默认值(getFCUnitByFCUnitId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/FCService/getFCUnitByFCUnitId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdResponse getFCUnitByFCUnitId(com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class FCUnitType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long unitIdField;
        
        private string unitNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long unitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("unitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
                this.RaisePropertyChanged("unitName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class FCCampaignType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long campaignIdField;
        
        private string campaignNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long campaignId {
            get {
                return this.campaignIdField;
            }
            set {
                this.campaignIdField = value;
                this.RaisePropertyChanged("campaignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string campaignName {
            get {
                return this.campaignNameField;
            }
            set {
                this.campaignNameField = value;
                this.RaisePropertyChanged("campaignName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        public getFCCampaignRequest() {
        }
        
        public getFCCampaignRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaigns", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FCCampaignType[] campaigns;
        
        public getFCCampaignResponse() {
        }
        
        public getFCCampaignResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, FCCampaignType[] campaigns) {
            this.ResHeader = ResHeader;
            this.campaigns = campaigns;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        public getFCCampaignIdRequest() {
        }
        
        public getFCCampaignIdRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getFCCampaignIdResponse() {
        }
        
        public getFCCampaignIdResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, long[] campaignIds) {
            this.ResHeader = ResHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignByFCCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignByFCCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] campaignIds;
        
        public getFCCampaignByFCCampaignIdRequest() {
        }
        
        public getFCCampaignByFCCampaignIdRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long[] campaignIds) {
            this.AuthHeader = AuthHeader;
            this.campaignIds = campaignIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCCampaignByFCCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCCampaignByFCCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("campaigns", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FCCampaignType[] campaigns;
        
        public getFCCampaignByFCCampaignIdResponse() {
        }
        
        public getFCCampaignByFCCampaignIdResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, FCCampaignType[] campaigns) {
            this.ResHeader = ResHeader;
            this.campaigns = campaigns;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitByFCCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitByFCCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long campaignId;
        
        public getFCUnitByFCCampaignIdRequest() {
        }
        
        public getFCUnitByFCCampaignIdRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long campaignId) {
            this.AuthHeader = AuthHeader;
            this.campaignId = campaignId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitByFCCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitByFCCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("units", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FCUnitType[] units;
        
        public getFCUnitByFCCampaignIdResponse() {
        }
        
        public getFCUnitByFCCampaignIdResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, FCUnitType[] units) {
            this.ResHeader = ResHeader;
            this.units = units;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitIdByFCCampaignIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitIdByFCCampaignIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long campaignId;
        
        public getFCUnitIdByFCCampaignIdRequest() {
        }
        
        public getFCUnitIdByFCCampaignIdRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long campaignId) {
            this.AuthHeader = AuthHeader;
            this.campaignId = campaignId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitIdByFCCampaignIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitIdByFCCampaignIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("unitIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] unitIds;
        
        public getFCUnitIdByFCCampaignIdResponse() {
        }
        
        public getFCUnitIdByFCCampaignIdResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, long[] unitIds) {
            this.ResHeader = ResHeader;
            this.unitIds = unitIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitByFCUnitIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitByFCUnitIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("unitIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] unitIds;
        
        public getFCUnitByFCUnitIdRequest() {
        }
        
        public getFCUnitByFCUnitIdRequest(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long[] unitIds) {
            this.AuthHeader = AuthHeader;
            this.unitIds = unitIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFCUnitByFCUnitIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getFCUnitByFCUnitIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("units", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FCUnitType[] units;
        
        public getFCUnitByFCUnitIdResponse() {
        }
        
        public getFCUnitByFCUnitIdResponse(com.baidu.api.sem.nms.v2.FCService.ResHeader ResHeader, FCUnitType[] units) {
            this.ResHeader = ResHeader;
            this.units = units;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCServiceChannel : com.baidu.api.sem.nms.v2.FCService.FCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.FCService.FCService>, com.baidu.api.sem.nms.v2.FCService.FCService {
        
        public FCServiceClient() {
        }
        
        public FCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCCampaign(com.baidu.api.sem.nms.v2.FCService.getFCCampaignRequest request) {
            return base.Channel.getFCCampaign(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCCampaign(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, out FCCampaignType[] campaigns) {
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCCampaignRequest();
            inValue.AuthHeader = AuthHeader;
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCCampaign(inValue);
            campaigns = retVal.campaigns;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdRequest request) {
            return base.Channel.getFCCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCCampaignId(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, out long[] campaignIds) {
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCCampaignId(inValue);
            campaignIds = retVal.campaignIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCCampaignByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdRequest request) {
            return base.Channel.getFCCampaignByFCCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCCampaignByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long[] campaignIds, out FCCampaignType[] campaigns) {
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignIds = campaignIds;
            com.baidu.api.sem.nms.v2.FCService.getFCCampaignByFCCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCCampaignByFCCampaignId(inValue);
            campaigns = retVal.campaigns;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCUnitByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdRequest request) {
            return base.Channel.getFCUnitByFCCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCUnitByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long campaignId, out FCUnitType[] units) {
            com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignId = campaignId;
            com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCUnitByFCCampaignId(inValue);
            units = retVal.units;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCUnitIdByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdRequest request) {
            return base.Channel.getFCUnitIdByFCCampaignId(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCUnitIdByFCCampaignId(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long campaignId, out long[] unitIds) {
            com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.campaignId = campaignId;
            com.baidu.api.sem.nms.v2.FCService.getFCUnitIdByFCCampaignIdResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCUnitIdByFCCampaignId(inValue);
            unitIds = retVal.unitIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdResponse com.baidu.api.sem.nms.v2.FCService.FCService.getFCUnitByFCUnitId(com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdRequest request) {
            return base.Channel.getFCUnitByFCUnitId(request);
        }
        
        public com.baidu.api.sem.nms.v2.FCService.ResHeader getFCUnitByFCUnitId(com.baidu.api.sem.nms.v2.FCService.AuthHeader AuthHeader, long[] unitIds, out FCUnitType[] units) {
            com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdRequest inValue = new com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.unitIds = unitIds;
            com.baidu.api.sem.nms.v2.FCService.getFCUnitByFCUnitIdResponse retVal = ((com.baidu.api.sem.nms.v2.FCService.FCService)(this)).getFCUnitByFCUnitId(inValue);
            units = retVal.units;
            return retVal.ResHeader;
        }
    }
}
