//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.baidu.api.sem.nms.v2.AdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.baidu.com/sem/nms/v2", ConfigurationName="AdService.AdService")]
    public interface AdService {
        
        // CODEGEN: 消息 addAdRequest 的包装名称(addAdRequest)以后生成的消息协定与默认值(addAd)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/addAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.addAdResponse addAd(com.baidu.api.sem.nms.v2.AdService.addAdRequest request);
        
        // CODEGEN: 消息 copyAdRequest 的包装名称(copyAdRequest)以后生成的消息协定与默认值(copyAd)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/copyAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.copyAdResponse copyAd(com.baidu.api.sem.nms.v2.AdService.copyAdRequest request);
        
        // CODEGEN: 消息 deleteAdRequest 的包装名称(deleteAdRequest)以后生成的消息协定与默认值(deleteAd)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/deleteAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.deleteAdResponse deleteAd(com.baidu.api.sem.nms.v2.AdService.deleteAdRequest request);
        
        // CODEGEN: 消息 getAdByAdIdRequest 的包装名称(getAdByAdIdRequest)以后生成的消息协定与默认值(getAdByAdId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/getAdByAdId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.getAdByAdIdResponse getAdByAdId(com.baidu.api.sem.nms.v2.AdService.getAdByAdIdRequest request);
        
        // CODEGEN: 消息 getAdByGroupIdRequest 的包装名称(getAdByGroupIdRequest)以后生成的消息协定与默认值(getAdByGroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/getAdByGroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdResponse getAdByGroupId(com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdRequest request);
        
        // CODEGEN: 消息 getAdIdByGroupIdRequest 的包装名称(getAdIdByGroupIdRequest)以后生成的消息协定与默认值(getAdIdByGroupId)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/getAdIdByGroupId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdResponse getAdIdByGroupId(com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdRequest request);
        
        // CODEGEN: 消息 replaceAdRequest 的包装名称(replaceAdRequest)以后生成的消息协定与默认值(replaceAd)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/replaceAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.replaceAdResponse replaceAd(com.baidu.api.sem.nms.v2.AdService.replaceAdRequest request);
        
        // CODEGEN: 消息 setAdStatusRequest 的包装名称(setAdStatusRequest)以后生成的消息协定与默认值(setAdStatus)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/setAdStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.setAdStatusResponse setAdStatus(com.baidu.api.sem.nms.v2.AdService.setAdStatusRequest request);
        
        // CODEGEN: 消息 updateAdRequest 的包装名称(updateAdRequest)以后生成的消息协定与默认值(updateAd)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="https://api.baidu.com/sem/nms/v2/AdService/updateAd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        com.baidu.api.sem.nms.v2.AdService.updateAdResponse updateAd(com.baidu.api.sem.nms.v2.AdService.updateAdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private string targetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
                this.RaisePropertyChanged("target");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adIdField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adId {
            get {
                return this.adIdField;
            }
            set {
                this.adIdField = value;
                this.RaisePropertyChanged("adId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class Failure : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private string positionField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
    public partial class ResHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private Failure[] failuresField;
        
        private int oprsField;
        
        private bool oprsFieldSpecified;
        
        private int oprtimeField;
        
        private bool oprtimeFieldSpecified;
        
        private int quotaField;
        
        private bool quotaFieldSpecified;
        
        private int rquotaField;
        
        private bool rquotaFieldSpecified;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("failures", Order=1)]
        public Failure[] failures {
            get {
                return this.failuresField;
            }
            set {
                this.failuresField = value;
                this.RaisePropertyChanged("failures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int oprs {
            get {
                return this.oprsField;
            }
            set {
                this.oprsField = value;
                this.RaisePropertyChanged("oprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprsSpecified {
            get {
                return this.oprsFieldSpecified;
            }
            set {
                this.oprsFieldSpecified = value;
                this.RaisePropertyChanged("oprsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int oprtime {
            get {
                return this.oprtimeField;
            }
            set {
                this.oprtimeField = value;
                this.RaisePropertyChanged("oprtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oprtimeSpecified {
            get {
                return this.oprtimeFieldSpecified;
            }
            set {
                this.oprtimeFieldSpecified = value;
                this.RaisePropertyChanged("oprtimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int quota {
            get {
                return this.quotaField;
            }
            set {
                this.quotaField = value;
                this.RaisePropertyChanged("quota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quotaSpecified {
            get {
                return this.quotaFieldSpecified;
            }
            set {
                this.quotaFieldSpecified = value;
                this.RaisePropertyChanged("quotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int rquota {
            get {
                return this.rquotaField;
            }
            set {
                this.rquotaField = value;
                this.RaisePropertyChanged("rquota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rquotaSpecified {
            get {
                return this.rquotaFieldSpecified;
            }
            set {
                this.rquotaFieldSpecified = value;
                this.RaisePropertyChanged("rquotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.baidu.com/sem/nms/v2")]
    public partial class AdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long adIdField;
        
        private bool adIdFieldSpecified;
        
        private long localIdField;
        
        private bool localIdFieldSpecified;
        
        private long groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private string titleField;
        
        private string displayUrlField;
        
        private string destinationUrlField;
        
        private string description1Field;
        
        private string description2Field;
        
        private byte[] imageDataField;
        
        private string imageUrlField;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long adId {
            get {
                return this.adIdField;
            }
            set {
                this.adIdField = value;
                this.RaisePropertyChanged("adId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adIdSpecified {
            get {
                return this.adIdFieldSpecified;
            }
            set {
                this.adIdFieldSpecified = value;
                this.RaisePropertyChanged("adIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long localId {
            get {
                return this.localIdField;
            }
            set {
                this.localIdField = value;
                this.RaisePropertyChanged("localId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool localIdSpecified {
            get {
                return this.localIdFieldSpecified;
            }
            set {
                this.localIdFieldSpecified = value;
                this.RaisePropertyChanged("localIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified {
            get {
                return this.groupIdFieldSpecified;
            }
            set {
                this.groupIdFieldSpecified = value;
                this.RaisePropertyChanged("groupIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string displayUrl {
            get {
                return this.displayUrlField;
            }
            set {
                this.displayUrlField = value;
                this.RaisePropertyChanged("displayUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string destinationUrl {
            get {
                return this.destinationUrlField;
            }
            set {
                this.destinationUrlField = value;
                this.RaisePropertyChanged("destinationUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string description1 {
            get {
                return this.description1Field;
            }
            set {
                this.description1Field = value;
                this.RaisePropertyChanged("description1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
                this.RaisePropertyChanged("description2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=10)]
        public byte[] imageData {
            get {
                return this.imageDataField;
            }
            set {
                this.imageDataField = value;
                this.RaisePropertyChanged("imageData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
                this.RaisePropertyChanged("imageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addAdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public addAdRequest() {
        }
        
        public addAdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, AdType[] adTypes) {
            this.AuthHeader = AuthHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class addAdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public addAdResponse() {
        }
        
        public addAdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, AdType[] adTypes) {
            this.ResHeader = ResHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copyAdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class copyAdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("groupIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] groupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("adIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adIds;
        
        public copyAdRequest() {
        }
        
        public copyAdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] groupIds, long[] adIds) {
            this.AuthHeader = AuthHeader;
            this.groupIds = groupIds;
            this.adIds = adIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copyAdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class copyAdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public copyAdResponse() {
        }
        
        public copyAdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class deleteAdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adIds;
        
        public deleteAdRequest() {
        }
        
        public deleteAdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds) {
            this.AuthHeader = AuthHeader;
            this.adIds = adIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class deleteAdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public deleteAdResponse() {
        }
        
        public deleteAdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdByAdIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdByAdIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adIds;
        
        public getAdByAdIdRequest() {
        }
        
        public getAdByAdIdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds) {
            this.AuthHeader = AuthHeader;
            this.adIds = adIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdByAdIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdByAdIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public getAdByAdIdResponse() {
        }
        
        public getAdByAdIdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, AdType[] adTypes) {
            this.ResHeader = ResHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdByGroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdByGroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long groupId;
        
        public getAdByGroupIdRequest() {
        }
        
        public getAdByGroupIdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long groupId) {
            this.AuthHeader = AuthHeader;
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdByGroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdByGroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public getAdByGroupIdResponse() {
        }
        
        public getAdByGroupIdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, AdType[] adTypes) {
            this.ResHeader = ResHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdIdByGroupIdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdIdByGroupIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long groupId;
        
        public getAdIdByGroupIdRequest() {
        }
        
        public getAdIdByGroupIdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long groupId) {
            this.AuthHeader = AuthHeader;
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAdIdByGroupIdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class getAdIdByGroupIdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adIds;
        
        public getAdIdByGroupIdResponse() {
        }
        
        public getAdIdByGroupIdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, long[] adIds) {
            this.ResHeader = ResHeader;
            this.adIds = adIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceAdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class replaceAdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] adIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long adId;
        
        public replaceAdRequest() {
        }
        
        public replaceAdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds, long adId) {
            this.AuthHeader = AuthHeader;
            this.adIds = adIds;
            this.adId = adId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceAdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class replaceAdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public replaceAdResponse() {
        }
        
        public replaceAdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAdStatusRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class setAdStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("statusTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatusType[] statusTypes;
        
        public setAdStatusRequest() {
        }
        
        public setAdStatusRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, StatusType[] statusTypes) {
            this.AuthHeader = AuthHeader;
            this.statusTypes = statusTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setAdStatusResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class setAdStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string response;
        
        public setAdStatusResponse() {
        }
        
        public setAdStatusResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, string response) {
            this.ResHeader = ResHeader;
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAdRequest", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateAdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public updateAdRequest() {
        }
        
        public updateAdRequest(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, AdType[] adTypes) {
            this.AuthHeader = AuthHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateAdResponse", WrapperNamespace="https://api.baidu.com/sem/nms/v2", IsWrapped=true)]
    public partial class updateAdResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.baidu.com/sem/common/v2")]
        public com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.baidu.com/sem/nms/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("adTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AdType[] adTypes;
        
        public updateAdResponse() {
        }
        
        public updateAdResponse(com.baidu.api.sem.nms.v2.AdService.ResHeader ResHeader, AdType[] adTypes) {
            this.ResHeader = ResHeader;
            this.adTypes = adTypes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdServiceChannel : com.baidu.api.sem.nms.v2.AdService.AdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdServiceClient : System.ServiceModel.ClientBase<com.baidu.api.sem.nms.v2.AdService.AdService>, com.baidu.api.sem.nms.v2.AdService.AdService {
        
        public AdServiceClient() {
        }
        
        public AdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.addAdResponse com.baidu.api.sem.nms.v2.AdService.AdService.addAd(com.baidu.api.sem.nms.v2.AdService.addAdRequest request) {
            return base.Channel.addAd(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader addAd(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, ref AdType[] adTypes) {
            com.baidu.api.sem.nms.v2.AdService.addAdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.addAdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adTypes = adTypes;
            com.baidu.api.sem.nms.v2.AdService.addAdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).addAd(inValue);
            adTypes = retVal.adTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.copyAdResponse com.baidu.api.sem.nms.v2.AdService.AdService.copyAd(com.baidu.api.sem.nms.v2.AdService.copyAdRequest request) {
            return base.Channel.copyAd(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader copyAd(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] groupIds, long[] adIds, out string response) {
            com.baidu.api.sem.nms.v2.AdService.copyAdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.copyAdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupIds = groupIds;
            inValue.adIds = adIds;
            com.baidu.api.sem.nms.v2.AdService.copyAdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).copyAd(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.deleteAdResponse com.baidu.api.sem.nms.v2.AdService.AdService.deleteAd(com.baidu.api.sem.nms.v2.AdService.deleteAdRequest request) {
            return base.Channel.deleteAd(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader deleteAd(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds, out string response) {
            com.baidu.api.sem.nms.v2.AdService.deleteAdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.deleteAdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adIds = adIds;
            com.baidu.api.sem.nms.v2.AdService.deleteAdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).deleteAd(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.getAdByAdIdResponse com.baidu.api.sem.nms.v2.AdService.AdService.getAdByAdId(com.baidu.api.sem.nms.v2.AdService.getAdByAdIdRequest request) {
            return base.Channel.getAdByAdId(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader getAdByAdId(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds, out AdType[] adTypes) {
            com.baidu.api.sem.nms.v2.AdService.getAdByAdIdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.getAdByAdIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adIds = adIds;
            com.baidu.api.sem.nms.v2.AdService.getAdByAdIdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).getAdByAdId(inValue);
            adTypes = retVal.adTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdResponse com.baidu.api.sem.nms.v2.AdService.AdService.getAdByGroupId(com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdRequest request) {
            return base.Channel.getAdByGroupId(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader getAdByGroupId(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long groupId, out AdType[] adTypes) {
            com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupId = groupId;
            com.baidu.api.sem.nms.v2.AdService.getAdByGroupIdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).getAdByGroupId(inValue);
            adTypes = retVal.adTypes;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdResponse com.baidu.api.sem.nms.v2.AdService.AdService.getAdIdByGroupId(com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdRequest request) {
            return base.Channel.getAdIdByGroupId(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader getAdIdByGroupId(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long groupId, out long[] adIds) {
            com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.groupId = groupId;
            com.baidu.api.sem.nms.v2.AdService.getAdIdByGroupIdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).getAdIdByGroupId(inValue);
            adIds = retVal.adIds;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.replaceAdResponse com.baidu.api.sem.nms.v2.AdService.AdService.replaceAd(com.baidu.api.sem.nms.v2.AdService.replaceAdRequest request) {
            return base.Channel.replaceAd(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader replaceAd(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, long[] adIds, long adId, out string response) {
            com.baidu.api.sem.nms.v2.AdService.replaceAdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.replaceAdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adIds = adIds;
            inValue.adId = adId;
            com.baidu.api.sem.nms.v2.AdService.replaceAdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).replaceAd(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.setAdStatusResponse com.baidu.api.sem.nms.v2.AdService.AdService.setAdStatus(com.baidu.api.sem.nms.v2.AdService.setAdStatusRequest request) {
            return base.Channel.setAdStatus(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader setAdStatus(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, StatusType[] statusTypes, out string response) {
            com.baidu.api.sem.nms.v2.AdService.setAdStatusRequest inValue = new com.baidu.api.sem.nms.v2.AdService.setAdStatusRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.statusTypes = statusTypes;
            com.baidu.api.sem.nms.v2.AdService.setAdStatusResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).setAdStatus(inValue);
            response = retVal.response;
            return retVal.ResHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        com.baidu.api.sem.nms.v2.AdService.updateAdResponse com.baidu.api.sem.nms.v2.AdService.AdService.updateAd(com.baidu.api.sem.nms.v2.AdService.updateAdRequest request) {
            return base.Channel.updateAd(request);
        }
        
        public com.baidu.api.sem.nms.v2.AdService.ResHeader updateAd(com.baidu.api.sem.nms.v2.AdService.AuthHeader AuthHeader, ref AdType[] adTypes) {
            com.baidu.api.sem.nms.v2.AdService.updateAdRequest inValue = new com.baidu.api.sem.nms.v2.AdService.updateAdRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.adTypes = adTypes;
            com.baidu.api.sem.nms.v2.AdService.updateAdResponse retVal = ((com.baidu.api.sem.nms.v2.AdService.AdService)(this)).updateAd(inValue);
            adTypes = retVal.adTypes;
            return retVal.ResHeader;
        }
    }
}
